<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getApplicationWithAdvert($limit){
		$qb = $this->createQueryBuilder('a');

		// On fait une jointure avec l'entité Advert avec pour alias « adv »
		$qb
			->innerJoin('a.advert', 'adv')
			->addSelect('adv')
		;

		// Puis on ne retourne que $limit résultats
		$qb->setMaxResult($limit);

		// Enfin, on retourne le résultat
		return $qb
			->getQuery()
			->getResult()
		;
	}
}
